#!/bin/bash

export LC_ALL="C"
set -euo pipefail

TOPIC='send-sms'

. "$(dirname "$(realpath "$0")")/lib/defaults"

USAGE="

  Listen on the request topic ($TOPIC)"

. "$(dirname "$(realpath "$0")")/lib/kafka-lib.sh"

(($# == 0)) || usage_exit

kcat_listen
