#!/bin/bash

export LC_ALL="C"
set -euo pipefail

. "$(dirname "$(realpath "$0")")/lib/defaults.sh"

TOPIC='sms-status'
USAGE="

  Listen on the response topic ($TOPIC)"

. "$(dirname "$(realpath "$0")")/lib/common.sh"

(($# == 0)) || usage_exit

kcat_listen
