#!/bin/bash

export LC_ALL="C"
set -euo pipefail

TOPIC='sms-status'

LIB_DIR="$(dirname "$(realpath "$0")")/lib"
. "$LIB_DIR/settings.sh"

USAGE="CLIENT CORREL STATUS [ERRTEXT ...]

  Fake a response from the SMS gateway

  POSITIONAL PARAMS
   CLIENT   Client ID
   CORREL   Correlation ID
   STATUS   Status to report back (SENT, etc)
   ERRTEXT  Optional error text (rest of line)"

. "$LIB_DIR/kafka-lib.sh"

(($# >= 3)) || usage_exit

CLIENT="$1"
CORREL="$2"
STATUS="$3"
(($# >= 4)) && shift 3 && ERRTEXT="$*" || ERRTEXT=""
 
printf '{ "client-id": "%s", "correl-id": "%s", "timestamp": "%s", "sms-status": "%s"%s }\n' \
	"$CLIENT" "$CORREL" "$(date -Is)" "$STATUS" "${ERRTEXT:+, \"error-text\": \"$ERRTEXT\"}" |
kcat_send
